### ISSUE TITLE
please upload test .model files.

### ISSUE THREAD

**Issue by rake93** [pz325/Coursera_NLP_MC#1]
please upload the test input files.
p1.model,
p2.model,
p3.model,
p1.gene.train,p2.gene.train,p3.gene.train

**Comment by pz325** [comment]
Setting TRAIN = True in p1.py, p2.py and p3.py, respectively, then these files are generated.

**Comment by rake93** [comment]
Hi Ping,

Thanks for your reply,

i tried to run the file p1.py. I'm getting below error, So do i need to
create any sample file?

would you please give me the steps to execute your programs? Since I'm new
to Python programming.

On Tue, Mar 26, 2013 at 1:25 PM, Ping Zou notifications@github.com wrote:

> Setting TRAIN = True in p1.py, p2.py and p3.py, respectively, then these
> files are generated.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pz325/Coursera_NLP_MC/issues/1#issuecomment-15445513
> .

## 

*Regards,
Rakesh.
http://j2eearchitec.blogspot.com/
*

**Comment by rake93** [comment]
Sorry i missed attachment..PFA screen shot

On Tue, Mar 26, 2013 at 1:58 PM, rakesh muppa rake.muppa@gmail.com wrote:

> Hi Ping,
> 
> Thanks for your reply,
> 
> i tried to run the file p1.py. I'm getting below error, So do i need to
> create any sample file?
> 
> would you please give me the steps to execute your programs? Since I'm new
> to Python programming.
> 
> On Tue, Mar 26, 2013 at 1:25 PM, Ping Zou notifications@github.comwrote:
> 
> > Setting TRAIN = True in p1.py, p2.py and p3.py, respectively, then these
> > files are generated.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/pz325/Coursera_NLP_MC/issues/1#issuecomment-15445513
> > .
> 
> ## 
> 
> *Regards,
> Rakesh.
> http://j2eearchitec.blogspot.com/
> *

## 

*Regards,
Rakesh.
http://j2eearchitec.blogspot.com/
*

**Comment by pz325** [comment]
See no image attachments. But:

edit line 34 of p1.py, setting TRAIN = True

then “python p1.py” to run the program. 

Training process reads "gene.train", and generates "p1.model and p1.gene.train"
Tagging process reads "gene.dev" (as test data), and "p1.model", and generates "gene_dev.p1.output".

Once you have training done, but to tag another set of test data, no need to run training again as generating p1.gene.train is time consuming. So it is then safe to set TRAIN to False and change test_data_filename (e.g. gene.test)

Hope it helps.

**Comment by rake93** [comment]
Thank you very much Ping..now its working...

On Tue, Mar 26, 2013 at 2:17 PM, Ping Zou notifications@github.com wrote:

> See no image attachments. But:
> 
> edit line 34 of p1.py, setting TRAIN = True
> 
> then “python p1.py” to run the program.
> 
> Training process reads "gene.train", and generates "p1.model and
> p1.gene.train"
> Tagging process reads "gene.dev" (as test data), and "p1.model", and
> generates "gene_dev.p1.output".
> 
> Once you have training done, but to tag another set of test data, no need
> to run training again as generating p1.gene.train is time consuming. So it
> is then safe to set TRAIN to False and change test_data_filename (e.g.
> gene.test)
> 
> Hope it helps.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pz325/Coursera_NLP_MC/issues/1#issuecomment-15447000
> .

## 

*Regards,
Rakesh.
http://j2eearchitec.blogspot.com/
*

**Comment by rake93** [comment]
which files do i need to submit for Assignment in Coursera?
output files or .py files.

Sorry for the trouble..i'm asking you too many questions.

On Tue, Mar 26, 2013 at 3:10 PM, rakesh muppa rake.muppa@gmail.com wrote:

> Thank you very much Ping..now its working...
> 
> On Tue, Mar 26, 2013 at 2:17 PM, Ping Zou notifications@github.comwrote:
> 
> > See no image attachments. But:
> > 
> > edit line 34 of p1.py, setting TRAIN = True
> > 
> > then “python p1.py” to run the program.
> > 
> > Training process reads "gene.train", and generates "p1.model and
> > p1.gene.train"
> > Tagging process reads "gene.dev" (as test data), and "p1.model", and
> > generates "gene_dev.p1.output".
> > 
> > Once you have training done, but to tag another set of test data, no need
> > to run training again as generating p1.gene.train is time consuming. So it
> > is then safe to set TRAIN to False and change test_data_filename (e.g.
> > gene.test)
> > 
> > Hope it helps.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/pz325/Coursera_NLP_MC/issues/1#issuecomment-15447000
> > .
> 
> ## 
> 
> *Regards,
> Rakesh.
> http://j2eearchitec.blogspot.com/
> *

## 

*Regards,
Rakesh.
http://j2eearchitec.blogspot.com/
*

**Comment by pz325** [comment]
tagging results should be OK. Coursera only score those results.

**Comment by rake93** [comment]
Hi Ping,

I got the below feedback when i submitted files..
1) gene_dev.p1.output,
2) gene_dev.p2.output,
3) gene_dev.p3.output

Failed to parse output data. Could not align gold standard and predictions
in line 1. Gold standard: Third Prediction file: BACKGROUND

On Tue, Mar 26, 2013 at 4:42 PM, Ping Zou notifications@github.com wrote:

> tagging results should be OK. Coursera only score those results.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pz325/Coursera_NLP_MC/issues/1#issuecomment-15452367
> .

## 

*Regards,
Rakesh.
http://j2eearchitec.blogspot.com/
*

**Comment by pz325** [comment]
You need tag gene.test and submit the corresponding results. Read the instruction.

**Comment by rake93** [comment]
Hi ping,

This is regarding Second assignment-NLP.

when i submit Part-2 output file, i got the below Feedback. i attached the
output files, if this file is wrong please let me know what to do.

Failed to parse output data. Sentence length does not match. Gold sentence
length 6, test sentence length 13. Sentence 'When was the bar-code invented
?'

On Wed, Mar 27, 2013 at 12:00 PM, Ping Zou notifications@github.com wrote:

> You need tag gene.test and submit the corresponding results. Read the
> instruction.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pz325/Coursera_NLP_MC/issues/1#issuecomment-15506389
> .

## 

*Regards,
Rakesh.
http://j2eearchitec.blogspot.com/
*
